@startuml

' typical MPD Display setup

skinparam defaultTextAlignment center
skinparam RectangleBackgroundColor white
skinparam DatabaseBackgroundColor white
skinparam AgentBackgroundColor white
skinparam ArrowColor black

!include <material/common>
!include <material/speaker>
!include <material/library_music>
!include <material/server>
!include <material/raspberrypi>
!include <material/wifi>
!include <material/tablet_android>
!include <material/laptop>
!include <material/usb>
!include <material/vector_rectangle>
!include <office/Devices/switch>
!include raspberry-pi.puml

together {
label browser as "<$ma_laptop>\nPhone/Laptop"
database music as "Music Source\n<$ma_library_music>"
}
frame pi as "<$raspberry-pi,scale=.5> Raspberry Pi" {
  agent mpd as "MPD"
  agent moode as "moOde Web"
  agent wakeup as "Wake-up\nscript"
}
label sound as "<$ma_speaker>\nSound System"
label mpddisp as "<$ma_tablet_android>\nMPD Display"

browser <-.-> moode
moode <--> mpd
music -.-> mpd
mpd --> sound : "DAC/RCA"
mpd <-.-> mpddisp
wakeup <--> mpd
wakeup --> mpddisp

@enduml
